### ISSUE TITLE
No async task available! (RuntimeError)

### ISSUE THREAD

**Issue by prateek-ap** [socketry/async#113]
Any one have any clue why this exception.
```
    14: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-websocket-0.18.0/lib/async/websocket/connection.rb:71:in `write'
    13: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/protocol-websocket-0.7.5/lib/protocol/websocket/connection.rb:182:in `write'
    12: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/protocol-websocket-0.7.5/lib/protocol/websocket/connection.rb:113:in `send_text'
    11: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/protocol-websocket-0.7.5/lib/protocol/websocket/connection.rb:80:in `write_frame'
    10: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/protocol-websocket-0.7.5/lib/protocol/websocket/framer.rb:70:in `write_frame'
     9: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/protocol-websocket-0.7.5/lib/protocol/websocket/frame.rb:209:in `write'
     8: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-io-1.30.2/lib/async/io/stream.rb:176:in `write'
     7: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-io-1.30.2/lib/async/io/stream.rb:155:in `flush'
     6: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-1.29.0/lib/async/semaphore.rb:80:in `acquire'
     5: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-io-1.30.2/lib/async/io/stream.rb:160:in `block in flush'
     4: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-io-1.30.2/lib/async/io/generic.rb:161:in `write'
     3: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-io-1.30.2/lib/async/io/generic.rb:62:in `block in wrap_blocking_method'
     2: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-io-1.30.2/lib/async/io/generic.rb:222:in `async_send'
     1: from /root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-1.29.0/lib/async/wrapper.rb:135:in `wait_writable'
/root/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-1.29.0/lib/async/task.rb:190:in `current': No async task available! (RuntimeError)
```

**Comment by ioquatix** [comment]
Are you using falcon?

**Comment by prateek-ap** [comment]
No, I am not using falcon.

**Comment by ioquatix** [comment]
You will need to run your websocket inside an `Async` block.

**Comment by prateek-ap** [comment]
I need to use websocket with following functionalities:
Websocket run with
- on_open
- on_close
- on_message
- send_message

**I have my async-websocket implementation like this, start method creates a new thread and runs async-websocket related functions inside that forever.
sizedQueue is a Queue which contains messages to be posted to channel. Exception is occurring at line `@ws.write msg`**
```
def start()
    Thread.new {
        Async do |task|
            endpoint = Async::HTTP::Endpoint.parse(URL)
            @ws = Async::WebSocket::Client.open(endpoint).connect(endpoint.authority, endpoint.path)
            
            if !@ws.closed?
                send_connection_success_message_to_channel()
            end

            
            event_task = task.async do
                Thread.new {
                    loop do
                        msg = sizedQueue.deq #thread blocks when the queue is empty
                        @ws.write msg # Exception occurring here
                    end
                } 
            end
             
            task.async do
                while message = @ws.read
                    process_message(message)
                end
            rescue EOFError => error
                start() #If connections drops this will restart the websocket connection, kind of :on_close
            end
        end
    }
end
```

@ioquatix Can you please help me out finding what's wrong in the above code snippet?

**Comment by ioquatix** [comment]
Here is a working example:

```
require 'async'
require 'async/http/endpoint'
require 'async/websocket/client'
require 'console'

# Console.logger.debug!

URL = "wss://echo.websocket.org"

def start(output)
  endpoint = Async::HTTP::Endpoint.parse(URL)
  socket = Async::WebSocket::Client.connect(endpoint) do |socket|
    Console.logger.info(socket, "Sending message")
    socket.write("Hello World")
    
    while message = socket.read
      Console.logger.info(socket, "Got response:", message)
    end
  end
end

Async do |task|
  while true
    begin
      start($stdout)
    rescue => error
      Console.logger.error(self, error)
      task.sleep 1
    end
  end
end
```
