### ISSUE TITLE
FiberError: fiber called across threads when using async inside a sidekiq worker

### ISSUE THREAD

**Issue by zhulik** [socketry/async#175]
Hello,

for some time I use async inside sidekiq jobs, each job starts it's own reactor using this simple server middleware:
```ruby
class Sidekiq::Middleware::Async::Server
  def call(_worker, _job, _queue)
    Async do
      yield
    ensure
      Grumlin.close # grumlin is my Gremlin client built on top of async-websocket
    end
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Middleware::Async::Server
  end
end
```
Code running in the job does not spawn any threads, but sidekiq itself is threaded, but I get `FiberError: fiber called across threads` from time to time.

Stacktrace:
```
File /app/vendor/bundle/ruby/3.1.0/gems/async-2.0.3/lib/async/condition.rb line 36 in transfer
File /app/vendor/bundle/ruby/3.1.0/gems/async-2.0.3/lib/async/condition.rb line 36 in transfer
File /app/vendor/bundle/ruby/3.1.0/gems/async-2.0.3/lib/async/notification.rb line 47 in block in transfer
File /app/vendor/bundle/ruby/3.1.0/gems/async-2.0.3/lib/async/notification.rb line 46 in each
File /app/vendor/bundle/ruby/3.1.0/gems/async-2.0.3/lib/async/notification.rb line 46 in transfer
File /app/vendor/bundle/ruby/3.1.0/gems/async-2.0.3/lib/async/scheduler.rb line 220 in select
File /app/vendor/bundle/ruby/3.1.0/gems/async-2.0.3/lib/async/scheduler.rb line 220 in run_once
File /app/vendor/bundle/ruby/3.1.0/gems/async-2.0.3/lib/async/scheduler.rb line 239 in run
File /app/vendor/bundle/ruby/3.1.0/gems/async-2.0.3/lib/kernel/async.rb line 48 in Async 
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/middleware/chain.rb line 179 in block in invoke
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb line 43 in block in execute
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/lock/while_executing.rb line 44 in block (2 levels) in execute
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/locksmith.rb line 204 in block (2 levels) in lock!
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/locksmith.rb line 275 in handle_primed
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/locksmith.rb line 257 in primed_async
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/locksmith.rb line 198 in call
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/locksmith.rb line 198 in block in lock!
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/locksmith.rb line 230 in enqueue
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/locksmith.rb line 195 in lock!
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/locksmith.rb line 106 in block in execute
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq.rb line 164 in block in redis
File /app/vendor/bundle/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb line 63 in block (2 levels) in with
File /app/vendor/bundle/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb line 62 in handle_interrupt
File /app/vendor/bundle/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb line 62 in block in with
File /app/vendor/bundle/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb line 59 in handle_interrupt
File /app/vendor/bundle/ruby/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb line 59 in with
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq.rb line 161 in redis
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/connection.rb line 19 in redis
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/locksmith.rb line 105 in execute
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/lock/while_executing.rb line 43 in block in execute
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/logging.rb line 142 in block in with_logging_context
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/logger.rb line 11 in with
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/logging.rb line 157 in call
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/logging.rb line 157 in with_configured_loggers_context
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/logging.rb line 141 in with_logging_context
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/lock/while_executing.rb line 42 in execute
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb line 43 in execute
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/middleware/server.rb line 27 in call
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/middleware.rb line 41 in block in call
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/logging.rb line 142 in block in with_logging_context
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/logger.rb line 11 in with
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/logging.rb line 157 in call
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/logging.rb line 157 in with_configured_loggers_context
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/logging.rb line 141 in with_logging_context
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/middleware.rb line 40 in call
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/middleware/chain.rb line 179 in block in invoke
File /app/vendor/bundle/ruby/3.1.0/gems/rollbar-3.3.1/lib/rollbar/plugins/sidekiq/plugin.rb line 11 in call
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/middleware/chain.rb line 179 in block in invoke
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/middleware/chain.rb line 182 in invoke
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 169 in block in process
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 136 in block (6 levels) in dispatch
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb line 112 in local
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 135 in block (5 levels) in dispatch
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/rails.rb line 14 in block in call
File /app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/execution_wrapper.rb line 91 in wrap
File /app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/reloader.rb line 72 in block in wrap
File /app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/execution_wrapper.rb line 91 in wrap
File /app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/reloader.rb line 71 in wrap
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/rails.rb line 13 in call
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 131 in block (4 levels) in dispatch
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 263 in stats
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 126 in block (3 levels) in dispatch
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/job_logger.rb line 13 in call
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 125 in block (2 levels) in dispatch
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb line 79 in global
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 124 in block in dispatch
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/job_logger.rb line 39 in prepare
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 123 in dispatch
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 168 in process
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 78 in process_one
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/processor.rb line 68 in run
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/component.rb line 8 in watchdog
File /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.4/lib/sidekiq/component.rb line 17 in block in safe_thread 
```

What would be the best way to debug and fix it? Reduce concurrency of sidekiq to 1 and spawn more processes instead?

**Comment by ioquatix** [comment]
Is any state shared between workers? i.e. global connection pool or something.

**Comment by zhulik** [comment]
Maybe unintentionally, each thread is supposed to have it's own connection pool
```ruby
        Thread.current.thread_variable_set(:grumlin_default_pool,
                                           Async::Pool::Controller.new(Grumlin::Client::PoolResource,
                                                                       limit: config.pool_size))
```

**Comment by ioquatix** [comment]
Is there any chance resources are being leaked across threads?

**Comment by ioquatix** [comment]
The stack trace tells me that you have a fiber, possibly from a different thread, waiting on a resource or condition of a different thread.

**Comment by ioquatix** [comment]
We could debug this by logging the thread the condition was created on and bombing out as soon as it fails:

```ruby
require 'async'

module CrossThreadBomb
	def initialize
		super
		@thread = Thread.current
	end
	
	def wait
		if Thread.current != @thread
			raise "Cross-thread bomb!"
		end
		
		super
	end
end

Async::Condition.prepend(CrossThreadBomb)

Async do
	condition = Async::Condition.new
	
	Thread.new do
		condition.wait
	end.join
end
```

**Comment by zhulik** [comment]
Thanks a lot! Unfortunately I can't reproduce the issue locally, I'll deploy your snippet and wait till it explodes

**Comment by zhulik** [comment]
Apparently this didn't help, I'm still getting exactly the same exception. Any hints what else classes I may monkey patch in the similar way?

**Comment by ioquatix** [comment]
Hmm, that's odd, I tested it locally and it blew up. Let me check it again.

**Comment by zhulik** [comment]
This snipped actually causes `Condition#transfer` to raise a `FiberError` once task is finished:
```ruby
require "async"

Async do |reactor|
  task = reactor.async { Async::Task.current.sleep(1) }

  Thread.new do
    Async do
      task.wait
    end
  end
end
```

```
Traceback (most recent call last):
        5: from /home/user/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/async-1.30.3/lib/async/task.rb:272:in `block in make_fiber'
        4: from /home/user/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/async-1.30.3/lib/async/task.rb:287:in `finish!'
        3: from /home/user/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/async-1.30.3/lib/async/condition.rb:62:in `signal'
        2: from /home/user/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/async-1.30.3/lib/async/condition.rb:62:in `each'
        1: from /home/user/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/async-1.30.3/lib/async/condition.rb:63:in `block in signal'
/home/user/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/async-1.30.3/lib/async/condition.rb:63:in `resume': fiber called across threads (FiberError)
```

**Comment by ioquatix** [comment]
Sorry, I didn't have time to look at this, I'll spend some time tonight.

**Comment by zhulik** [comment]
You were absolutely right, the pool created in one thread may have been memoized and used from another thread. I removed the memoization and it fixed the issue

**Comment by jhass** [comment]
For future minds that find this first while searching for the error message, for me the trigger was the Faraday adapter, see https://github.com/socketry/async-http-faraday/issues/31
