### ISSUE TITLE
Async block does not complete if fiber count > 128

### ISSUE THREAD

**Issue by keithrbennett** [socketry/async#346]
I am experimenting with Async for the first time, and may very well be missing something simple, but I cannot get my script to complete if I configure it to create more than 128 fibers. I am unable to upload the script so I will paste it here. This is running on a 2023 MacBook Air (Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 arm64).

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'async'
require 'async/http/internet'

def get_responses_using_fibers(count)
  puts("Getting #{count} responses using fibers.")
  url = "https://httpbin.org/delay/0.001"
  responses = []

  Async do
    puts("Starting Async block.")
    begin
      internet = Async::HTTP::Internet.new
      response_count = 0
      count.times do
        Async do
          begin
            response = internet.get(url)
            response_count += 1
            puts("Response count: #{response_count}. Received response: #{response.status}")
            responses << response.status
          rescue => e
            puts("Error during request: #{e.message}")
          end
        end
      end
    rescue => e
      puts("Error during outer: #{e.message}")
    ensure
      internet&.close
    end
  end.wait

  puts("Ending Async block.")
  responses
end

count = ARGV.first ? ARGV.first.to_i : 129
get_responses_using_fibers(count)
puts('Done.')
```

When I specify 128, I get this:

```
Getting 128 responses using fibers.
Starting Async block.
Response count: 1. Received response: 200
...
Response count: 128. Received response: 200
Ending Async block.
Done.
```

For both Ruby 3.2.0 and 3.3.4, when I specify 129, I see this on the output, and the program hangs:

```
Getting 129 responses using fibers.
Starting Async block.
Response count: 1. Received response: 200
...
Response count: 129. Received response: 200
```

When I press Ctrl-C, I see this:

```
^C/Users/kbennett/.rvm/gems/ruby-3.3.4/gems/async-2.16.1/lib/async/scheduler.rb:317:in `select': Interrupt
	from /Users/kbennett/.rvm/gems/ruby-3.3.4/gems/async-2.16.1/lib/async/scheduler.rb:317:in `run_once!'
	from /Users/kbennett/.rvm/gems/ruby-3.3.4/gems/async-2.16.1/lib/async/scheduler.rb:353:in `run_once'
	from /Users/kbennett/.rvm/gems/ruby-3.3.4/gems/async-2.16.1/lib/async/scheduler.rb:408:in `block in run'
	from /Users/kbennett/.rvm/gems/ruby-3.3.4/gems/async-2.16.1/lib/async/scheduler.rb:386:in `block in run_loop'
	from /Users/kbennett/.rvm/gems/ruby-3.3.4/gems/async-2.16.1/lib/async/scheduler.rb:383:in `handle_interrupt'
	from /Users/kbennett/.rvm/gems/ruby-3.3.4/gems/async-2.16.1/lib/async/scheduler.rb:383:in `run_loop'
	from /Users/kbennett/.rvm/gems/ruby-3.3.4/gems/async-2.16.1/lib/async/scheduler.rb:407:in `run'
	from /Users/kbennett/.rvm/gems/ruby-3.3.4/gems/async-2.16.1/lib/kernel/async.rb:34:in `Async'
	from ./async-129-fibers-error.rb:12:in `get_responses_using_fibers'
	from ./async-129-fibers-error.rb:41:in `<main>'
```

Am I doing something wrong, or is this a bug in the library?

**Comment by ioquatix** [comment]
As requests are live, you need to ensure they are finished (graceful) or closed (immediate termination):

```ruby
begin
  response = internet.get(url)
  response_count += 1
  puts("Response count: #{response_count}. Received response: #{response.status}")
  responses << response.status
rescue => e
  puts("Error during request: #{e.message}")
ensure
  response&.finish
end
```

**Comment by keithrbennett** [comment]
That worked, thank you! Sorry, I should have RTFM'ed more.

**Comment by ioquatix** [comment]
No problem :)
